[[memory-access-types]]
==== Memory Access Types

LoongArch supports three types of memory access: **C**oherent **C**ached (CC), **S**trongly-ordered **U**n**C**ached (SUC) and **W**eakly-ordered **U**n**C**ached (WUC).
The memory access type used for a location is associated with the virtual address, which is determined by the Memory Access Type field.
The relationship of the memory access type and `MAT` field is: `0` - SUC, `1` - CC, `2` - WUC, and `3` - reserved.
The memory access type setting process is transparent to the application.

When using consistent cacheable access type, the accessed object can be either the final memory object or the caches.
This type of access is usually used to access faster.

When using SUC or WUC access, the final memory object can only be directly accessed.
The difference between the two is: SUC access meets sequential consistency, that is, all accesses are executed in strict accordance with the order in the program and the next memory access operation cannot be started before the current memory access operation is completely completed.
While the WUC read access allows speculative execution, and WUC written data can be merged inside the processor core to a larger scale (such as a Cache line) and then written out in a burst mode.
Subsequent writes in the merge process can overwrite the data written earlier.

In LoongArch, only SUC memory access instructions must not have side effects, that is, such instructions cannot be predictive executed.
Software can use this feature to access I/O devices in the system through SUC type memory access instructions.
However, LoongArch allows SUC fetch instruction operations to have side effects.
This means that the access type is a SUC type of fetch instruction operation, even if it originates from the result of branch prediction, it is allowed to be executed.
In order to prevent the out-of-core memory access operations generated by such speculative execution from erroneously entering the illegal physical address space, it is necessary to filter out the risky accesses, This will be done on the chip.

The WUC type of access is usually used to accelerate the access to UC memory data, such as video memory data.

===== Cache Coherency Maintenance of Instruction Cache

The Cache coherency between the instruction Cache of a certain processor core and the Cache in other processor cores or Cache Coherenr I/O Master must be maintained by hardware.

The Cache coherency maintenance between the instruction Cache and the data Cache within the processor core can be implemented as hardware maintenance.
This means that for the self-modifying code, the software does not need to use the `CACOP` instruction to maintain the Cache coherency between the instruction Cache and the data Cache within the same core.
However, due to the pipeline structure and speculative instruction fetching behavior, the software still needs to use the `IBAR` instruction to ensure that the instruction fetching must be able to see the execution effect of the store instruction.
