[[configuration-register-instruction-debug-support]]
=== Configuration Register Instruction Debug Support

The configuration register instruction is in principle used without cross-chip access, but in order to meet the need for debugging and other functions, cross-chip access is supported here using multiple register addresses.
It is worth noting that such registers can only be written, not read.

Together with the existing inter-processor interrupts and other registers that can be accessed across slices, all such registers and their addresses are listed below.

[[processor-core-inter-processor-communication-registers-3]]
.Processor core inter-processor communication registers
[%header,cols="3m,^1m,^1,3"]
|===
^d|Name
d|Offset Address
|Read/Write
^|Description

|IPI_Send
|0x1040
|WO
|32-bit interrupt distribution register

`[31]`: wait for completion flag; when set to `1` it will wait for the interrupt to take effect

`[30:26]`: reserved

`[25:16]`: processor core number

`[15:5]`: reserved

`[4:0]`: interrupt vector number, corresponding to the vector in `IPI_Status`

|Mail_Send
|0x1048
|WO
|64-bit MailBox Cache register

`[63:32]`: MailBox data

`[31]`: wait for completion flag; when set to `1` it will wait for the write to take effect

`[30:27]`: write data mask; each bit indicates that the bytes corresponding to the 32-bit write data will not really be written to the target address, such as `1000b` means write the `0`-`2` bytes, `0000b` means write all `0`-`3` bytes

`[26]`: reserved

`[25:16]`: processor core number

`[15:5]`: reserved

`[4:2]`: MailBox number

`0` - MailBox0 low 32-bit

`1` - MailBox0 high 32-bit

`2` - MailBox1 low 32-bit

`3` - MailBox1 high 32-bit

`4` - MailBox2 low 32-bit

`5` - MailBox2 high 32-bit

`6` - MailBox3 low 32-bit

`7` - MailBox4 high 32-bit

`[1:0]`: reserved

|FREQ_Send
|0x1058
|WO
|32-bit frequency enable register

`[31]`: wait for completion flag; when set to `1` it will wait for the setting to take effect

`[30:27]`: write data mask; each bit indicates that the bytes corresponding to the 32-bit write data will not really be written to the target address, such as `1000b` means write the `0`-`2` bytes, `0000b` means write all `0`-`3` bytes

`[26]`: reserved

`[25:16]`: processor core number

`[15:5]`: reserved

`[4:0]`: write to the corresponding processor core private frequency configuration register

`CSR[0x1050]`

|ANY_Send
|0x1158
|WO
|64-bit register access register

`[63:32]`: write data

`[31]`: wait for completion flag; when set to `1` it will wait for the interrupt to take effect

`[30:27]`: write data mask; each bit indicates that the bytes corresponding to the 32-bit write data will not really be written to the target address, such as `1000b` means write the `0`-`2` bytes, `0000b` means write all `0`-`3` bytes

`[26]`: reserved

`[25:16]`: destination processor core number

`[15:0]`: offset address of the register to be written
|===
