[[exception-priority]]
==== Exception Priority

The exception priority follows two basic principles: first, the interrupt priority is higher than the exception; second, for the exception, the highest priority is detected in the fetching stage, followed by the priority detected in the decoding stage, and the priority detected in the execution stage.

For exceptions detected in the fetching stage: the highest priority is given to the fetch operation watchpoint exception, the second highest priority is given to the fetch operation address error exception, the second highest priority is given to TLB-related exceptions, and the lowest priority is given to the machine error exception.

The exceptions that can be detected in the decoding stage are mutually exclusive, so there is no need to consider the priority between them.

Only memory access instructions may trigger multiple exceptions at the same time during the execution stage, with the following priorities in descending order: **A**ddress a**L**ignment fault **E**xception (ALE) caused by unaligned addresses for memory access instructions requesting alignment addresses > **AD**dress error **E**xception (ADE) > **B**ound **C**heck **E**xception (BCE){empty}footnote:[It is generated only when it is a memory access instruction of bound class.] > TLB-related exceptions{empty}footnote:[The definition of TLB-related exceptions dictates that only one TLB-related exception will be generated by a single memory access instruction in any case.] > **A**ddress a**L**ignment fault **E**xception (ALE) caused by addresses that span two pages of different Cache attributes for memory access instructions allowing non-alignment addresses.
