[[internal-device-address-routing]]
=== Internal Device Address Routing

Multiple devices within the MISC low-speed device block are distinguished by the bits [18:16] of the address bits, and different devices support only specific types of access. The device routing and supported access types are shown in the following table.
[[misc-Low-speed-device-address-routing-and-access-types]]
.MISC Low-speed device address routing and access types
[%header,cols="1,^1m,^1m,^1m,^1m,^1m"]
|===
|bit[18:16]
|0
|1
|2
|5
|6

|Device
|UART
|I2C
|PWM
|ACPI/RTC
|GPIO

|Read/Write
|B
|B
|W
|W
|B
|===

For UART, I2C, PWM, and ACPI/RTC, they require further routing due to the inclusion of multiple controllers. The internal routing of these device blocks is shown in the fllow table The number of routing address bits required varies from one device block to another.

[[misc-Low-speed-device-address-routing]]
.MISC Low-speed device address routing
[%header,cols="1m,^1m,^1m,^1m,^1m,^1m,^1m"]
|===
|
|0
|1
|2
|3
|4
|5

|UART(bit[9:8])
|UART0
|UART1
|UART2
|UART3
d|-
d|-

|I2C(bit[10:8])
|I2C0
|I2C1
|I2C2
|I2C3
|I2C4
|I2C5

|PWM(bit[9:8])
|PWM0
|PWM1
|PWM2
|PWM3
d|-
d|-

|ACPI/RTC(bit[8])
|ACPI
|RTC
d|-
d|-
d|-
d|-
|===

These low-speed devices are described separately in subsequent sections.

