[[exception-status]]
==== Exception Status (`ESTAT`)

This register records the status information of the exceptions, including the first and second level encoding of the triggered exceptions, and the status of each interrupt.

[[definition-of-exception-status-register]]
.Definition of exception status register
[%header,cols="2*^1m,^1,5"]
|===
d|Bits
d|Name
|Read/Write
|Description

|1:0
|IS[1:0]
|RW
|The status bits of the two software interrupts.
Bit `0` and `1` correspond to `SWI0` and `SWI1` respectively.

Software interrupt setting is also done by these two bits, writing `1` sets the interrupt, and writing `0` clears the interrupt.

|12:2
|IS[12:2]
|R
|The interrupt status bit.
`1` indicates that the corresponding interrupt is set up.
There is 1 inter-processor interrupt (IPI), 1 timer interrupt (TI), 1 performance counter overflow interrupt (PCOV), 8 hardware interrupts (HWI0-HWI7).

In line-based interrupt mode, the hardware only records each interrupt source per clock cycle to these bits.
The requirement that all interrupts must be level interrupts at this time is guaranteed by the interrupt source and is not maintained here.

|15:13
|0
|R0
|Reserved field.
Return `0` if read this field, and software is not allowed to change its value.

|21:16
|Ecode
|R
|Exception encoding.
When an exception is triggered: if it is a TLB refill exception or a machine error exception, this field remains unchanged; otherwise, the hardware writes the value defined in the `Ecode` column in the following table to this field according to the exception type.

|30:22
|EsubCode
|R
|Exception sub encoding.
When an exception is triggered: if it is a TLB refill exception or a machine error exception, the field remains unchanged; otherwise, the hardware writes the value defined in the `EsubCode` column in the following table to this field according to the exception type.

|31
|0
|R0
|Reserved field.
Return `0` if read this field and software is not allowed to change its value.
|===

[[table-of-exception-encoding]]
.Table of exception encoding
[%header,cols="3*^1m,3"]
|===
|Ecode
|EsubCode
d|Exception Code
|Exception Type

|0x0
|
|INT
|**INT**errupt only when `CSR.ECFG.VS=0`.

|0x1
|
|PIL
|**P**age **I**nvalid for **L**oad

|0x2
|
|PIS
|**P**age **I**nvalid for **S**tore

|0x3
|
|PIF
|**P**age **I**nvalid for instruction **F**etch

|0x4
|
|PME
|**P**age **M**odified **E**xception

|0x5
|
|PNR
|**P**age **N**on-**R**eadable

|0x6
|
|PNX
|**P**age **N**on-e**X**ecutable

|0x7
|
|PPI
|**P**age **P**rivilege level **I**llegal

.2+|0x8
|0
|ADEF
|**AD**dress **E**rror for instruction **F**etch

|1
|ADEM
<d|**AD**dress **E**rror for **M**emory access

|0x9
|
|ALE
|**AL**ignment **E**rror

|0xA
|
|BCE
|**B**ound **C**heck **E**xception

|0xB
|
|SYS
|**SYS**tem call

|0xC
|
|BRK
|**BR**ea**K**point

|0xD
|
|INE
|**I**nstruction **N**on-**E**xistent

|0xE
|
|IPE
|**I**nstruction **P**rivilege **E**rror

|0xF
|
|FPD
|**FP**U **D**isabled

|0x10
|
|SXD
|L**SX** unit **D**isabled

|0x11
|
|ASXD
|L**ASX** unit **D**isabled

.2+|0x12
|0
|FPE
|**FP**U **E**xception

|1
|VFPE
<d|**V**ector **FP**U **E**xception

.2+|0x13
|0
|WPEF
|**W**atch**P**oint **E**xception for **F**etch watchpoint

|1
|WPEM
<d|**W**atch**P**oint **E**xception for **M**emory load/store watchpoint

|0x14
|
|BTD
|L**BT** unit **D**isabled

|0x15
|
|BTE
|L**BT** unit **E**xception

|0x16
|
|GSPR
|**G**uest **S**ensitive **P**rivileged **R**esource exception

|0x17
|
|HVC
|**H**yper**V**isor **C**all

.2+|0x18
|0
|GCSC
|**G**uest **C**SR modified, **S**oftware **C**aused

|1
|GCHC
<d|**G**uest **C**SR modified, **H**ardware **C**aused

|0x1A-0x3E
|
|
|Reserved
|===
