[[real-time-temperature-collection]]
=== Real-time Temperature Collection

Two temperature sensors are integrated inside the Loongson 3A5000, which can be observed through the sampling register starting at `0x1FE00198`, and can be controlled using the flexible high and low temperature interrupt alarm or auto-tuning function.
The corresponding bits of the temperature sensors in the sampling register are as follows (base address is `0x1FE00000`, offset address is `0x0198`):

[[description-of-temperature-collection-register]]
.Description of temperature collection register
[%header,cols="^1m,2m,^1,^1m,3"]
|===
d|Bit Field
^d|Name
|Read/Write
d|Reset Value
^|Description

|24
|Thsens0_overflow
|R
|
|Temperature sensor 0 overflow

|25
|Thsens1_overflow
|R
|
|Temperature sensor 1 overflow

|47:32
|Thsens0_out
|R
|
|Temperature sensor 0 centigrade temperature

`Node temperature=Thens0_out *731/0x4000-273`

Temperature range: `-40` degree - `125` degree

|65:48
|Thsens1_out
|R
|
|Temperature sensor 1 centigrade temperature

`Node temperature=Thens0_out *731/0x4000-273`

Temperature range: `-40` degree - `125` degree
|===

The control registers can be set to enable over preset temperature interrupt, under preset temperature interrupt and high temperature auto down function.

In addition, the current centigrade temperature can be read directly using the new centigrade temperature register.
This register can also be accessed using a read operation with base address `0x1FE00000` or `0x3FF00000`, or directly using a configuration register instruction with offset `0x0428`.
The register is described as follows:

[[extended-io-interrupt-trigger-register-2]]
.Extended I/O interrupt trigger register
[%header,cols="3m,^1m,^1,3"]
|===
^d|Name
d|Offset Address
|Read/Write
^|Description

|Thsens_Temperature
|0x0428
|R
|Temperature sensor centigrade temperature
|===
