[[tlb-entry-low-order-bits]]
==== TLB Entry Low-order Bits (`TLBELO0`, `TLBELO1`)

`TLBELO0` and `TLBELO1` registers contain the information related to the physical page number of the low-order bits of the TLB table entry during executing TLB-related instructions.
Since TLB adopts a dual-page structure, the low-order bits of TLB table entry corresponds to the odd and even physical page table entries, where the even page information is in `TLBELO0` and the odd page information is in `TLBELO1`.
`TLBELO0` and `TLBELO1` registers have exactly the same format definition, and the definition of each field is in the table.

When `CSR.TLBRERA.IsTLBR=0`, and when executing the `TLBWR` and `TLBFILL` instructions, and the written values of the `G`, `PFN0`, `V0`, `PLV0`, `MATO`, `D0`, `NR0`, `NX0`, `RPLV0`, `PFN1`, `V1`, `PLV1`, `MATl`, `D1`, `NR1`, `NX1`, and `RPLV1` fields of the TLB table entry come from `TLBELOO` and `TLBELO1` fields, respectively.

When executing the `TLBRD` instruction, the above information read from the TLB table entry is written to the corresponding fields in the `TLBELO0` and `TLBELO1` registers one by one.

[[definition-of-tlb-entry-low-order-bits-register-in-la64]]
.Definition of TLB entry low order bits in LA64
[%header,cols="2*^1m,^1,5"]
|===
d|Bits
d|Name
|Read/Write
|Description

|0
|V
|RW
|**V**alid bit (`V`) of the page table entry.

|1
|D
|RW
|**D**irty bit (`D`) of the page table entry.

|3:2
|PLV
|RW
|**P**rivilege **L**e**V**el of the page table entry (`PLV`).

|5:4
|MAT
|RW
|**M**emory **A**ccess **T**ype (`MAT`) of the page table entry.

|6
|G
|RW
|**G**lobal flag bit (`G`) of the page table entry.

When executing the `TLBFILL` and `TLBWR` instructions, the `G` bit in `TLBELO0` and `TLBELO1` is `1` only if both bits are `1`.

The `G` bit of the page table entry filled into the TLB will be `1` only when the `G` bit in both `TLBELO0` and `TLBELO1` is `1`.

When executing the `TLBRD` instruction, when the `G` bit of the TLB table entry read is `1`, the `G` bits in `TLBELO0` and `TLBELO1` are set to `1` at the same time.

|11:7
|0
|R
|Read-only constant `0`, writing to this field is ignored.

|PALEN-1:12
|PPN
|RW
|**P**hysical **P**age **N**umber (`PPN`) of the page table.

|60:PALEN
|0
|R
|Read-only constant `0`, writing to this field is ignored.

|61
|NR
|RW
|**N**on-**R**eadable bit (`NR`) of the page table entry.

|62
|NX
|RW
|**N**on-e**X**ecutable bit (`NX`) of the page table entry.

|63
|RPLV
|RW
|**R**estricted **P**rivilege **L**e**V**el enable (`RPLV`) of the page table.
When `RPLV=0`, the page table entry can be accessed by any program whose privilege level is not lower than `PLV`; when `RPLV=1`, the page table entry can only be accessed by programs whose privilege level is equal to `PLV`.
|===

[[definition-of-tlb-entry-low-order-bits-register-in-la32]]
.Definition of TLB entry low order bits in LA32
[%header,cols="2*^1m,^1,5"]
|===
d|Bits
d|Name
|Read/Write
|Description

|0
|V
|RW
|**V**alid bit (`V`) of the page table entry.

|1
|D
|RW
|**D**irty bit (`D`) of the page table entry.

|3:2
|PLV
|RW
|**P**rivilege **L**e**V**el (`PLV`) of the page table entry.

|5:4
|MAT
|RW
|**M**emory **A**ccess **T**ype (`MAT`) of the page table entry.

|6
|G
|G
|**G**lobal flag bit (`G`) of the page table entry.

When executing the `TLBFILL` and `TLBWR` instructions, the `G` bit in `TLBELO0` and `TLBELO1` is `1` only if both bits are `1`.

The `G` bit of the page table entry filled into the TLB will be `1` only when the `G` bit in both `TLBELO0` and `TLBELO1` is `1`.

When executing the `TLBRD` instruction, when the `G` bit of the TLB table entry read is `1`, the `G` bits in `TLBELO0` and `TLBELO1` are set to `1` at the same time.

|7
|0
|R
|Read-only constant `0`, writing to this field is ignored.

|31:8
|PPN
|RW
|**P**hysical **P**age **N**umber (`PPN`) of the page table.
|===
