[[ht-controller-frequency-division-and-enable-control]]
=== HT Controller Frequency Division and Enable Control

The frequency division mechanism of the HT controller is similar to the others.
The two HT controllers can be controlled separately.
The settings are made using the corresponding bits in the function configuration register.
Its base address is `0x1fe00000`,It can also be accessed using the configuration register instruction (IOCSR), and offset address `0x0180`.

[[function-configuration-register-3]]
.Function configuration register
[%header,cols="^1m,2m,^1,^1m,3"]
|===
d|Bit Field
^d|Name
|Read/Write
d|Reset Value
^|Description

|26:24
|HT0_freq_scale_ctrl
|RW
|3'b111
|HT Controller 0 frequency division

|27
|HT0_clken
|RW
|1'b1
|Whether to enable HT0

|30:28
|HT1_freq_scale_ctrl
|RW
|3'b011
|HT Controller 1 frequency division

|31
|HT1_clken
|RW
|1'b1
|Whether to enable HT1
|===

In line with other frequency division controls, the HT controller clock can be adjusted from `(frequency division control value + 1)/8` to `1/(frequency division control value + 1)` by setting the clock frequency after frequency division through a register.
This register is located in other function configuration register.
The base address is `0x1fe00000`,It can also be accessed using the configuration register instruction (IOCSR), and the offset address is `0x0420`.

Note that since the HT core clock is derived from the Node clock, it is also affected by the Node clock frequency division.

[[other-function-configuration-register-5]]
.Other function configuration register
[%header,cols="^1m,2m,^1,^1m,3"]
|===
d|Bit Field
^d|Name
|Read/Write
d|Reset Value
^|Description

|39:38
|freqscale_mode_HT
|RW
|0x0
|Frequency adjustment mode selection for each HT

`0`: `(n+1)/8`

`1`: `1/(n+1)`
|===
