[[example-of-bridge-device-address-space-allocation]]
=== Example of Bridge Device Address Space Allocation

Access to the bridge chip devices is mainly done through the PCI MEM space. The software can assign any access address for each device on the bridge chip within this address segment. The internal PCI devices of the bridge chip include: GPU/DC, GMEM, PCIE, USB, SATA, GMAC, HDA/AC97, LPC, SPI, all of which can be seen through lspci. The access addresses of these devices (except LPC) can be dynamically assigned by software. One way of allocation is as follows: by scanning the PCI bus and reading the configuration space of each device (PCI mode orientation) to get the size of MEM space and I/O space used by each device, the system software allocates the appropriate size of MEM space from the address 0x40000,0000–0x7fff,fff, and from 0x1800, 0000–0x19ff,ffff. The system software allocates the appropriate size of I/O space (PCIE devices) from 0x40000,0000–0x7fff,ffff.

In addition to these PCI type devices, the bridge also contains some devices that are accessed using fixed addresses, such as: interrupt controllers, HPET controllers, confbus In addition to these PCI-type devices, the bridge also contains devices that are accessed using fixed addresses, such as: interrupt controllers, HPET controllers, confbus configuration registers, MISC low-speed device blocks, and LPCs.

The following two tables give an example of an address allocation for a bridge chip fixed address device and a PCI device, along with their address space size and supported access types. For the access types, B indicates byte access (1byte), H indicates half-word access (2byte), W indicates word access (4byte), D indicates double-word access (8byte), Q indicates 4-word access (16byte), and C indicates cacheline access.

[[bridge-piece-fixed-address-device-address-space]]
.Bridge piece fixed address device address space
[%header,cols="^1m,^2m,^1m,1"]
|===
|Module
|Address space
|Address space size
|  Access type

|INT
|0x1000,0000–0x1000,0fff
|4K
|BHW

|HPET
|0x1000,1000–0x1000,1fff
|4K
|BW

|CONF REG
|0x1001,0000–0x1001,ffff
|64K
|BHW

|MISC
|0x1008,0000–0x100f,ffff
|512K
|BW

|LPC REG
|0x1000,2000–0x1000,2fff
|4K
|W

|LPC MEM
|0x1200,0000–0x13ff,ffff
|32M
|BHWDQC

|LPC I/O
|0x1800,0000–0x1800,ffff
|64K
|B

|LPC TPM
|0x1801,0000–0x1801,ffff
|64K
|B
|===

[[bridge-chip-PCI-device-address-space-allocation-example]]
.Bridge chip PCI device address space allocation example
[%header,cols="^1m,^2m,^1m,1"]

|===
|Module
|Address space
|Address space size
|  Access type

|GPU
|0x5ff4,0000–0x5ff7,ffff
|256K
|W

|DC
|0x5ff8,0000–0x5ff8,ffff
|64K
|W

|Graphic Memory
|0x4000,0000–0x4fff,ffff
|256M
|BHWDQC

|PCIE I/O
|0x1802,0000–0x19ff,ffff
|32M
|BHW

|PCIE MEM
|0x6000,0000–0x7fff,ffff
|512M
|BHW

|SPI MEM
|0x5e00,0000–0x5eff,ffff
|16M
|BHWDQC

|USB0-EHCI
|0x5fd0,0000–0x5fd0,7fff
|32K
|W

|USB0-OHCI
|0x5fd0,8000–0x5fd0,ffff
|32K
|W

|USB1-EHCI
|0x5fd1,0000–0x5fd1,7fff
|32K
|W

|USB1-OHCI
|0x5fd1,8000–0x5fd1,ffff
|32K
|W

|SATA0
|0x5fe0,0000–0x5fe0,1fff
|8K
|W

|SATA1
|0x5fe0,2000–0x5fe0,3fff
|8K
|W

|SATA2
|0x5fe0,4000–0x5fe0,5fff
|8K
|W

|GMAC0
|0x5fe1,0000–0x5fe1,7fff
|32K
|W

|GMAC1
|0x5fe1,8000–0x5fe1,ffff
|32K
|W

|HDA
|0x5fe2,0000–0x5fe2,ffff
|64K
|BHW

|AC97
|0x5fe3,0000–0x5fe3,ffff
|64K
|W

|SPI REG
|0x5ff1,1000–0x5ff1,1fff
|4K
|B
|===

The size of the address space of the above devices is fixed, except for PCIE MEM and Graphic Memory, which can be changed by software.

The BIOS needs to modify the MASK value of the BAR register 2/3 of the GPU configuration header by accessing the bridge configuration register GMEM_BAR_MASK to configure the size of Graphic Memory. Graphic Memory size, and then the software will get the graphic memory size through PCI The software then scans through the PCI to obtain the size of the graphics memory.

In the case of using a PCIE external discrete graphics card, the discrete graphics memory space that comes with the discrete graphics card is located in the PCIE MEM address space and is managed as a PCIE device.
