[[debug-support-for-configuration-register-instructions]]
=== Debug Support for Configuration Register Instructions

The configuration register instruction is in principle used without cross-chip access, but in order to meet the needs for debugging, etc., cross-chip access is supported here by using multiple register addresses.
It is worth noting that such registers can only be written, not read.

In addition to `IPI_Send`, `Mail Send`, `Freq Send` mentioned in the previous section, there is also an `Any Send` register available with the following address.

[[processor-core-inter-processor-communication-registers-2]]
.Processor core inter-processor communication registers
[%header,cols="3m,^1m,^1,3"]
|===
^d|Name
d|Offset Address
|Read/Write
^|Description

|ANY_Send
|0x1158
|WO
|64-bit register access register

`[63:32]`: data being written

`[31]`: wait for completion flag; when set to 1 it will wait for the interrupt to take effect

`[30:27]`: write data mask; each bit indicates that the bytes corresponding to the 32-bit write data will not really be written to the target address, such as `1000b` means write the `0`-`2` bytes, `0000b` means write all `0`-`3` bytes

`[26]`: reserved

`[25:16]`: destination processor core number

`[15:0]`: offset address of the register to be written
|===
