= LoongArch Processor SMBIOS Spec
Loongson Technology Corporation Limited
v1.00
:docinfodir: ../themes
:docinfo: shared
:doctype: book
:toc: left

This document defines LoongArch processor-specific data block to supplement the upstream definition of SMBIOS structure Type 44 (Processor Additional Information, section 7.45 in SMBIOS specification V3.5.0 or later).

== Symbols

* *DQWORD* +
128-bits (In the SMBIOS specification, WORD is 16-bits, DWORD is 32-bits, and QWORD is 64-bits).


== Vendor Name register and CPU Name register

The LoongArch CPUs designed by Loongson have two registers representing Machine Vendor Name and CPU Name, both of which are DQWORD-format NUL-terminated ASCII string values, located at offsets 0x10 and 0x20 of the IOCSR space respectively.

== LoongArch Processor-specific Block Structure
[%header,cols="^1,^1,^1,^1,3"]
|===
|Offset
|Name
|Length
|Value
^|Description

|00h
|Block Length
|BYTE
|Varies (N)
|Length of Processor-specific Data

|01h
|Processor Type
|BYTE
|Varies
|The processor architecture delineated by this Processor-specific Block (See SMBIOS Table 131). 0x9 means LoongArch32 and 0x10 means LoongArch64.

|02h
|Processor-Specific Data
|N BYTEs
|Varies
|Processor-specific data.

|03h
|Reserved
|BYTE
|Varies
|Reserved.

|04h
|Machine Vendor ID
|DQWORD
|Varies
|The manufacturer vendor ID of the processor. +
It is semantically equivalent to the value at the offset 0x10 of the IOCSR space on a Loongson CPU.

|14h
|CPU ID
|DQWORD
|Varies
|The CPU ID used for this LoongArch processor manufacturer to mark different CPU types or CPU instances. +
It is semantically equivalent to the value at the offset 0x20 of the IOCSR space on a Loongson CPU.

|24h
|ISA extensions support
|DWORD
|Bit-field
|The bit field [3:0] indicates support for the existing LoongArch standard ISA extensions. It is modeled after the LoongArch EUEN register (CSR 0x2), and meaning of each bit is the same as defined for the EUEN register. +
Setting a bit in this field indicates that this system supports the corresponding ISA extension.
|===
