[[pcie-controller]]
== PCIE Controller (`D9:F0`, `D10:F0`, `D11:F0`, `D12:F0`, `D13:F0`, `D14:F0`, `D15:F0`, `D16:F0`, `D17:F0`, `D18:F0`, `D19:F0`, `D20:F0`)

The PCIEs of the bridge chip are divided into 5 groups: `PCIE_F0`, `PCIE_F1`, `PCIE_H`, `PCIE_G0`, `PCIE_G1`, with a total of 32 lanes.
Each group of PCIE interfaces has its own corresponding control port.
The bridge contains 12 PCIE control ports (ports), namely port 0, port 1, port 2, port 3 of `PCIE_F0`, port 0, port 1 of `PCIE_F1`, port 0, port 1 of `PCIE_G0`, port 0, port 1 of `PCIE_G1`, port 0, port 1 of `PCIE_H`, port 1 of `PCIE_H`.
Each port corresponds to a PCIE controller, and each PCIE controller contains a TYPE1 type PCI configuration header.

`PCIE_F0` includes 4 lanes and can be used as one x4 PCIE or 4 x1 PCIEs.
Among them, port 0 controls lane0 in non x4 mode, port 0 controls lane0, and lane0-3 in x4 mode.
In non-x4 mode, port 1 controls lane1, port In non-x4 mode, port 1 controls lane1, port 2 controls lane2, and port 3 controls lane3.

`PCIE_F1` includes 4 lanes, which can be used as one x4 PCIE or 2 x1 PCIEs.
Among them, port 0 controls lane0 in non lane0 in non-x4 mode and lane0-3 in x4 mode.
In non-x4 mode, port 1 controls lane1, lane2 and lane3 are not available.

`PCIE_H` includes 8 lanes and can be used as one x8 PCIE or 2 x4 PCIEs.
Among them, port 0 controls lane0-3 in non port 0 controls lane0-3 in non-x8 mode and lane0-7 in x8 mode.
In non-x8 mode, port 1 controls lane4-7.

`PCIE_G0` includes 8 lanes, which can be used as one x8 PCIE or two x4 PCIEs.
Among them, port 0 controls lane4-7 in Port 0 controls lane0-3 in non-x8 mode and lane0-7 in x8 mode.
In non-x8 mode, port 1 controls lane4-7.

`PCIE_G1` includes 8 lanes, which can be used as one x8 PCIE or two x4 PCIEs.
Among them, port 0 controls lane4-7 in port 0 controls lane0-3 in non-x8 mode and lane0-7 in x8 mode.
In non-x8 mode, port 1 controls lane4-7.

The PCIE controller of the bridge chip can be used only as RC, not as EP.

The configuration methods supported by PCIE and the corresponding control ports are shown in the tables below.

[[configuration-methods-and-control-ports-supported-by-pcie-f0]]
.Configuration methods and control ports supported by `PCIE_F0`
[cols="4*^1"]
|===
|lane0
|lane1
|lane2
|lane3

4+|x4 (P0)

|x1 (P0)
|x1 (P1)
|x1 (P2)
|x1 (P3)
|===

[[configuration-methods-and-control-ports-supported-by-pcie-f1]]
.Configuration methods and control ports supported by `PCIE_F1`
[cols="4*^1"]
|===
|lane0
|lane1
|lane2
|lane3

4+|x4 (P0)

|x1 (P0)
|x1 (P1)
|
|
|===

[[configuration-methods-and-control-ports-supported-by-pcie-g0-pcie-g1-and-pcie-h]]
.Configuration methods and control ports supported by `PCIE_G0`, `PCIE_G1` and `PCIE_H`

[cols="8*^1"]
|===
|lane0
|lane1
|lane2
|lane3
|lane4
|lane5
|lane6
|lane7

8+|x8 (P0)

4+|x4 (P0)
4+|x4 (P1)
|===

include::pcie-controller/pci-configuration-register.adoc[]

include::pcie-controller/address-space-division.adoc[]

include::pcie-controller/special-notes.adoc[]
